---
title: "Analysis Run Summary"
author: "FGCZ - Witold Wolski wew@fgcz.ethz.ch"
date: "25 November 2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
params:
  dataStart: NULL
  dataEnd: NULL
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

dataStart <- params$dataStart
dataEnd <- params$dataEnd

```

# Filter missigness


```{r naHeatmap}
ph <- dataStart$get_Plotter()$NA_heatmap()
```

```{r heatmapAllNAs, out.width = "85%",  fig.cap="before NA filtering"}
print(ph)
```



```{r}
sumarStart <- dataStart$get_Summariser()
sumarStart$hierarchy_counts()

LFQService::table_facade(sumarStart$hierarchy_counts(),
             caption = "Nr Proteins and peptides before missigness filtering.")

```



```{r}
LFQService::table_facade( sumarStart$hierarchy_counts_sample("wide"),
             caption = "NR Proteins and peptides by sample.")

```

```{r hierarchyCountsSampleBarplot, fig.cap="Number of quantified peptides and proteins per sample."}
sumarStart$hierarchy_counts_sample("plot")
```



\newpage


# Filtered data

```{r}
dataRemoved <- dataStart$filter_difference( dataEnd )
remSum <- dataRemoved$get_Summariser()
LFQService::table_facade(remSum$hierarchy_counts(),
             caption = "Numbers of proteins and peptides after removing sparse peptide quants and filtering for 2 peptides per protein" )
```

```{r removedHeatmap}
p <- dataRemoved$get_Plotter()$NA_heatmap()
```

```{r fig.cap="Missigness patterns for peptides of proteins removed from analysis.", fig.with=7, fig.height=8}
print(p)
```



# Left Proteins

```{r}
LFQService::table_facade(dataEnd$get_Summariser()$hierarchy_counts(),
             caption = "Numbers of proteins and peptides after filtering for 2 peptides per protein")

```


```{r}
LFQService::table_facade(dataEnd$get_Summariser()$hierarchy_counts_sample("wide"),
             caption = "Numbers of proteins and peptides after filtering for 2 peptides per protein by sample")

```


\newpage

```{r createHetmap}
x <-  dataEnd$get_Plotter()$NA_heatmap()
```


```{r NA_heatmapAfterFiltering,  fig.cap="Missigness heatmap after NA filtering."}
print(x)
```

\clearpage

