---
title: "Auxiliary - Euro Bioconductor 2020"
author: "Witold Wolski"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: 
    keep_tex: yes
vignette: >
  %\VignetteIndexEntry{Auxiliary - Euro Bioconductor 2020}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---



The R-package for **pro**teomics **l**abel **f**ree **qua**ntification `prolfqua` (read: prolevka) evolved from functions and code snippets used to visualize and analyze label-free quantification data. To compute protein fold changes among treatment conditions, we first used t-test or linear models and then used functions implemented in the package limma to obtain moderated p-values. We evaluated [MSStats]( 10.18129/B9.bioc.MSstats), [ROPECA](10.1038/s41598-017-05949-y) or [MSqRob](https://github.com/statOmics/MSqRob) all implemented in R, with the idea to integrate the various approaches. Although all these packages are written in R, model specification, input, and output formats differ widely and wildly, making our first attempt to use the original implementations challenging. Therefore, and also to better understand the algorithms used, we attempted to reimplement those methods, where possible. The R-package prolfqua is the outcome of this venture.

When developing _prolfqua_, we draw inspiration from packages such as _sf_, which uses data in a long tidy table format, _dplyr_ for data transformation _ggplot2_ for visualization. In the long table format, each column stores a different attribute, e.g., there is only a single column with the intensities.
In _prolfqua_, the data needed for analysis is represented using a single data-frame in long format and an _R6_ configuration object. The configuration annotates the data-frame, i.e., specifies what information is in which column. The use of an annotated table makes integrating new data if provided in long formatted tables simple. Therefore, all that is needed to incorporate Spectronaut, Skyline text output, or __MSStats__ inputs is to update the configuration object. For software like MaxQuant writing the data in a wide table format, with several intensity columns, one for each sample, we implemented methods that transform the data into a long format. Relying on the long tidy data table format enabled us to easily access various useful data manipulation and visualization methods implemented in the R packages _dplyr_ and _ggplot2_.

A further design decision was to embraces R's linear model formula interface, including the _lme4_ mixed effect models formula interface. R's formula interface for linear models is flexible, widely used, and well documented. These interfaces allow specifying a wide range of essential models, including parallel designs, factorial designs, repeated measurements, and many more. Since `prolfqua` uses R modeling infrastructure directly, we can fit all these models to proteomics data.
This is not easily possible with other package dedicated to proteomics data analysis. For instance, MSStats, although using the same modeling infrastructure, supports only a subset of possible models. _limma_ supports the R formula interface but not for linear mixed models. Since _ROPECA_ relies on _limma_, it is limited to the same set of models. _MSqRob_ allows specifying fixed and random effects but using their own model specification, and it is unclear how interactions among factors can be specified, estimated, or tested.

The use of R's formula interface does not limit `prolfqua` to the output provided by the R modelling infrastructure. `prolfqua` implements p-value moderations and computes probabilities of differential regulation, as suggested by _ROPECA_. Last but not least, ANOVA analysis or model selection using the likelihood ratio test for thousand of proteins can also be performed.
To use `prolfqua` knowledge of the R regression model infrastructure is of advantage. Acknowledging the formula interface's complexity, we will provide an MSstats emulator, which derives the model formula from an MSstats formatted input file.

We benchmarked all the methods implemented in prolfqua: linear models, mixed effect models, p-value moderation, ROPECA, and Bayesian regression models implemented in _brms_ using a benchmark dataset, enabling us to evaluate the practical relevance of these methods.

Finally, `prolfqua` supports the LFQ data analysis workflow elements, e.g., computing coefficients of Variations (CV) for peptide and proteins, sample size estimation, visualization, and summarization of missing data, summarization of intensities, multivariate analysis, etc. It also implements various protein intensity summarization and inference methods, e.g., top 3, or Tukeys median polish.

Our package makes it relatively easy to perform proteomics data analysis to generate visualizations and reports using Rmarkdown. We will continue extending the package's functionality. The package can be installed from [www.github.com/wolski/prolfqua](www.github.com/wolski/prolfqua).
