---
title: "Project meeting (bioinfo) Agenda"
author: "WEW"
date: "17/09/2019"
output: beamer_presentation
vignette: >
  %\VignetteIndexEntry{Project meeting (bioinfo) Agenda}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Introduction

Agenda for project kickoff meeting - bioinformatics part.

## Goal

- Save time 
- Improve quality of services
- Ensure reproducibility

## How?

- Keep it short (15-30 minutes) by follow an agenda
- Give _statistical_ guidance
- Get all the information you need to perform an analysis


# Motivation

- Incomplete information causes that analysis is delayed or has to be redone.
- Information extracted in little bits - some of it in e-mails, b-fabric comments. 
  - but was it project or order comment?
- how to find it?


# Aim of meeting

## Document

- which protein database to use
- which condition and how many samples to use for the QC
- collect all the parameters for sample size estimation
- specify the hypothesis to be tested
- specify the design of the main experiment
- document all the names of the factors and factor levels

# Conclusion

- Helps to prepare for meeting
- Focuses and streamlines discussion
- Tested on a few projects
- Agenda is still evolving

# TPF update

TPF - technology platform fund (50k)

To improve LFQ data analysis and reporting.

$\approx 8k$ spend on Lucas Kook, $\approx 12k$ on Jonas Grossman, $\approx 30k$ still available.

# TPF update

- QC and sample size estimation
- Hypothesis testing using linear models
  - using linear models and moderated p-values
  - using mixed effects linear models
  - using ROPECA
- GSEA and ORA analysis with Webgestalt and sigora

# Outlook

- Improve sample size estimation report (make it interactive).
- b-fabric integration.
- Alternative normalization, aggregations, models etc.
- More model diagnostics.
- Improving table formatting and data visualization.
- more downstream analysis.

# 


A work by :

Witek Wolski, Lukas Kook, Paolo Nanni and Christian Panse

$~$

$~$

$~$

$~$

_Thank you for listening_


