---
title: "Modelling Dataset with two Factors."
author: "Witold Wolski"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
vignette: |
  %\VignetteIndexEntry{Modelling dataset with two Factors.}  
  %\VignetteEncoding{UTF-8}   
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


# Model Fitting

```{r specifyModel}
library(prolfqua)
library(tidyverse)
conflicted::conflict_prefer("filter", "dplyr")

data("data_Yeast2Factor")

pMerged <- data_Yeast2Factor
pMerged$data$Run_ID <- as.numeric(pMerged$data$Run_ID)
pMerged$config$table$getWorkIntensity()
pMerged$factors()


formula_Batches <-
  strategy_lm("transformedIntensity ~ condition_ * batch_ ")

# specify model definition
modelName  <- "Model"
DEBUG <- TRUE

Contrasts <- c("Glucose - Ethanol" = "condition_Glucose - condition_Ethanol",
               "p2370 - p2691" = "batch_p2370 - batch_p2691",
               "Glucose_vs_Ethanol_gv_p2370" = "`condition_Glucose:batch_p2370` - `condition_Ethanol:batch_p2370`",
               "Glucose_vs_Ethanol_gv_p2691" = "`condition_Glucose:batch_p2691` - `condition_Ethanol:batch_p2691`",
               "Interaction" = "`Glucose_vs_Ethanol_gv_p2370` - `Glucose_vs_Ethanol_gv_p2691`"
)



```



```{r buildModel}

mod <- prolfqua::build_model(
  pMerged$data,
  formula_Batches,
  subject_Id = pMerged$config$table$hierarchyKeys() )

```



```{r anovaPvaluePlots, fig.cap="p-value distributions for ANOVA analysis."}
mod$anova_histogram()
```

## ANOVA

Examine proteins with a significant interaction between the two factors treatment and batch.

```{r anovaAnalysis}
ANOVA <- mod$get_anova()
ANOVA %>% dplyr::filter(factor == "condition_:batch_") %>% arrange(FDR.Pr..F.) %>% head(5)
protIntSig <- ANOVA %>% dplyr::filter(factor == "condition_:batch_") %>%
  dplyr::filter(FDR.Pr..F. < 0.05)
protInt <-  pMerged$get_copy()
protInt$data <- protInt$data[protInt$data$protein_Id %in% protIntSig$protein_Id,]
```


```{r fig.with=15, fig.height=15, fig.cap="Proteins with FDR < 0.5 for condition batch interaction in ANOVA."}
ggpubr::ggarrange(plotlist = protInt$get_Plotter()$boxplots()$boxplot)
```

# Compute contrasts

```{r computeModeratedContrasts}
contr <- prolfqua::ContrastsModerated$new(prolfqua::Contrasts$new(mod, Contrasts))
#contr$get_contrasts_sides()
contrdf <- contr$get_contrasts()
```

```{r}
plotter <- contr$get_Plotter()
plotter$volcano()
plotter$ma_plot()

```



## Annalyse contrasts with missing data imputation

```{r}
pMerged$config$table$fkeysDepth()
#ContrastsSimpleImpute$debug("get_contrasts")
contrSimple <- ContrastsSimpleImpute$new(pMerged, Contrasts)
contrdfSimple <- contrSimple$get_contrasts()
pl <- contrSimple$get_Plotter()
pl$histogram_estimate()
pl$volcano()

```


## Merge nonimputed and imputed data.

```{r}

dim(contr$get_contrasts())
dim(contrSimple$get_contrasts())

mergedContrasts <- prolfqua::addContrastResults(prefer = contr, add = contrSimple)$merged
cM <- mergedContrasts$get_Plotter()
plot <- cM$volcano()
plot$FDR
```



### Look at Proteins with significant interaction term.

```{r}

sigInteraction <- mergedContrasts$contrast_result %>% 
  filter(contrast == "Interaction" & FDR < 0.2)

protInt <-  pMerged$get_copy()
protInt$data <- protInt$data[protInt$data$protein_Id %in% sigInteraction$protein_Id,]

protInt$get_Plotter()$raster()
#ggplot(data=protInt$data ,aes(x=sampleName,y=protein_Id,fill=transformedIntensity))+
#  geom_tile()   + scale_fill_distiller(palette = "RdYlBu") +
#  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

hm <- protInt$get_Plotter()$heatmap()

```



```{r interactionHeatmap, fig.cap="Proteins with significant Interactions"}
hm
```
