---
title: "Benchmarking the proDA package using the Ionstar Dataset"
author: "FGCZ - (Draft)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      toc_collapsed: true
papersize: a4
geometry: margin=.5in
vignette: >
  %\VignetteIndexEntry{Benchmarking the proDA package using the Ionstar Dataset} 
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
evalAll <- require(proDA)

```

# Setting up analysis


```{r normalizeDataUsingProlfqua, eval=evalAll}
library(proDA)
library(tidyverse)
library(prolfqua)

# Read in MaxQuant files
datadir <- file.path(find.package("prolfquaData") , "quantdata")
inputMQfile <-  file.path(datadir,
                          "MAXQuant_IonStar2018_PXD003881.zip")
inputAnnotation <- file.path(datadir, "annotation_Ionstar2018_PXD003881.xlsx")



mqdata <- tidyMQ_ProteinGroups(inputMQfile)

mqdata <- mqdata %>% filter(!grepl("REV__", mqdata$proteinID))
mqdata <- mqdata %>% filter(!grepl("CON__", mqdata$proteinID))

annotation <- readxl::read_xlsx(inputAnnotation)
res <- add_annotation(
  mqdata,
  annotation,
  fileName = "raw.file"
)
res <- filter(res, nr.peptides > 1)
config <- prolfqua::AnalysisTableAnnotation$new()
config$factors[["dilution."]] = "sample"
config$fileName = "raw.file"
config$workIntensity = "mq.protein.lfq.intensity"
config$hierarchy[["proteinID"]] = "proteinID"

config <- prolfqua::AnalysisConfiguration$new(config)



lfqdata <- setup_analysis(res, config)

lfq <- LFQData$new(lfqdata, config)
lfq$remove_small_intensities()

tr <- lfq$get_Transformer()
tr$log2()
lfqhum <- lfq$get_subset(filter(lfq$data, grepl("HUMAN", lfq$data$proteinID)))

tr$robscale_subset(lfqhum$get_Transformer()$log2()$lfq)
lfqtrans <- tr$lfq

```





```{r createSummarizedExperiment, eval=evalAll}
library(SummarizedExperiment)
wide <- lfqtrans$to_wide(as.matrix = TRUE)
library(SummarizedExperiment)
ann <- data.frame(wide$annotation)
rownames(ann) <- wide$annotation$sampleName

se <- SummarizedExperiment(SimpleList(LFQ=wide$data), colData = ann)
se

```




Both input types are also accepted by `proDA`.

```{r runProda, eval=evalAll, include=TRUE}
# Not Run
fit <- proDA(se, design = ~ dilution. - 1,data_is_log_transformed = TRUE)
contr <- list()
contr[["dilution_(9/7.5)_1.2"]] <- data.frame(contrast = "dilution_(9/7.5)_1.2", test_diff(fit, contrast = "dilution.e - dilution.d"))
contr[["dilution_(7.5/6)_1.25"]] <- data.frame(contrast = "dilution_(7.5/6)_1.25", test_diff(fit, contrast = "dilution.d - dilution.c"))
contr[["dilution_(6/4.5)_1.3(3)"]] <- data.frame(contrast = "dilution_(6/4.5)_1.3(3)", test_diff(fit, contrast ="dilution.c - dilution.b"))
contr[["dilution_(4.5/3)_1.5"]] <- data.frame(contrast = "dilution_(4.5/3)_1.5", test_diff(fit, contrast ="dilution.b - dilution.a" ))

bb <- bind_rows(contr)
# End Not Run

```


# Defining Contrasts and computing group comparisons

# Benchmarking

```{r setUPBenchmark, eval = evalAll}
library(prolfqua)

bb$name %>% unique() %>% length()
ttd <- prolfqua::ionstar_bench_preprocess( bb , idcol = "name" )

benchmark_proDA <- make_benchmark(ttd$data,
                                   contrast = "contrast",
                                toscale = c("pval"),
                                fcestimate = "diff",
                                benchmark = list(
                                  list(sc = "diff", desc = TRUE),
                                  list(sc = "t_statistic", desc = TRUE),
                                  list(sc = "scaled.pval", desc = TRUE)
                                ),  
                                model_description = "proDA",
                                model_name = "proDA",
                                FDRvsFDP = list(list(sc = "adj_pval", desc = FALSE))
, hierarchy = c("name"), summarizeNA = "t_statistic"
)

sum(benchmark_proDA$smc$summary$name)
sumarry <- benchmark_proDA$smc$summary
table_facade(sumarry, caption = "nr of proteins with 0, 1, 2, 3 missing contrasts.")

```


```{r prepBenchmarkforComparison, include= FALSE, eval = evalAll}
  xdd <- ttd$data %>% dplyr::rename(protein_Id = name ,
                                    contrast = contrast,
                                    estimate = diff,
                                    statistic = t_statistic,
                                    p.value = pval,
                                    FDR = adj_pval  
  )
  
  benchmark2_proDA <- make_benchmark(xdd, model_description = "MSStats", model_name = "MSStats")
  saveRDS(benchmark2_proDA, file = "inst/Benchresults/benchmark2_proDA.RDS")

```

```{r rocCurve, fig.cap="ROC curves", eval = evalAll}
res <- benchmark_proDA$pAUC_summaries()
res$barp
```

```{r pAUC02, fig.cap="plot ROC curves", eval = evalAll}
#res$ftable
benchmark_proDA$plot_ROC(xlim = 0.2)
```

```{r fdrfdp, fig.cap = "plot FDR vs FDP",eval = evalAll}
benchmark_proDA$plot_FDRvsFDP()
```

```{r fdptpr,eval = evalAll}
benchmark_proDA$plot_FDPvsTPR()
```
