---
title: "Untitled"
author: "Witold Wolski"
date: "16/11/2020"
output:
  pdf_document: 
    keep_tex: yes
  html_document: default
---

The package for **pro**teomics **l**abel **f**ree **qua**ntification `prolfqua` (read: prolevka) evolved from functions and code snippets used to visualize and analyze label free quantification data. To compute protein fold changes among treatment conditions, we first used t-test or linear models, and then used functions implemented in the package limma to obtain moderated p-values. We evaluated [MSStats]( 10.18129/B9.bioc.MSstats), [ROPECA](10.1038/s41598-017-05949-y) or [MSqRob](https://github.com/statOmics/MSqRob) all implemented in R, with the idea to integrate the various approaches. Although all these packages are written in R, model specification, input and output formats among them differ widely and wildly, which made our first attempt to use the original implementations challenging. Therefore, and also to understand the algorithms used, we attempted to reimplement those methods, where possible. The R-package prolfqua is the outcome of this venture.

When developing _prolfqua_, we draw inspiration from packages such as _sf_, which use data in a long table format, _dplyr_ for data transformation and _ggplot2_ for visualization. In the long table format each column stores a different attribute, e.g. there is only a single column with the intensities.
In _prolfqua_ the data needed for analysis is represented using a single data-frame in long format and an _R6_ configuration object. The configuration annotates the table, i.e. specifies what information is in which column. The use of an annotated table makes integrating new data if provided in long formatted tables simple. Therefore, all that is needed to incorporate Spectronaut, Skyline text output, or __MSStats__ inputs is to update the configuration object. For software like MaxQuant writing the data in a wide table format, with several intensity columns, one for each sample, we implemented methods that transform the data into a long format. Relying on the long data table format enabled us to easily access a large variety of useful data manipulation and visualizations methods implemented in the R packages _dplyr_ and _ggplot2_.

A further design decision, which sets `prolfqua` apart is that it embraces R's linear model formula interface, including the _lme4_ mixed effect models formula interface. R's formula interface for linear models is flexible, widely used and well documented. These interfaces allow specifying a wide range of essential models including parallel designs, factorial designs, repeated measurements and many more. Since `prolfqua` uses R modelling infrastructure directly, we can fit all these models to proteomics data.
This is not easily possible with any other package dedicated to proteomics data analysis. For instance, MSStats, although using the same modelling infrastructure, supports only a subset of possible models. Limma, supports the R formula interface but not for linear mixed models. Since _ROPECA_ relies on _limma_ it is limited to the same set of models. _MSqRob_ allows specifying fixed and random effects, however it is unclear how interactions among factors can be specified, estimated or tested.

The use of R's formula interface does not limit `prolfqua` to the output provided by the R modelling infrastructure. `prolefqua`  implements p-value moderations, and computes probabilities of differential regulation, as suggested by ROPECA. Last but not least, ANOVA analysis or model selection using the likelihood ratio test for thousand of proteins can also be performed. 
To use `prolfqua` knowledge of the R regression model infrastructure is of advantage. Acknowledging the complexity of the formula interface, we provide an MSstats emulator, which derives the model formula from an MSstats formatted input file.

We benchmarked all the methods implemented in prolfqua: linear models, mixed effect models, p-value moderation, ROPECA, as well as Bayesian regression models implemented in _brms_ using a benchmark dataset, enabling us to evaluate the practical relevance of these methods.  

Last but not least, `prolfqua` supports elements of the LFQ data analysis workflow, e.g. computing coefficients of Variations (CV) for peptide and proteins, sample size estimation, visualization and summarization of missing data, summarization of intensities, multivariate analysis, etc. It also implements various protein intensity summarization and inference methods, e.g. top 3, or Tukeys median polish.

Our package makes it relatively easy to perform proteomics data analysis. We continue extening the functionality of the package, i.e. currently we are adding methods for count data modelling. The package can be installed from [www.github.com/wolski/prolfqua](www.github.com/wolski/prolfqua).

