---
title: "Example of data preprocessing for PRM data"
author: "Functional Genomics Center Zurich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
vignette: >
  %\VignetteIndexEntry{Example of data preprocessing for PRM data}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
echo = TRUE,
message = FALSE,
warning = FALSE,
fig.width = 10,
fig.height = 10
)
```


Example of visualizing and normalizing PRM data using an internal CiRT peptides (S. Parker 2015 MCP).

```{r loadPackages}
rm(list = ls())
library(conflicted)
library(tidyverse)
library(readxl)
library(yaml)
library(LFQService)
conflict_prefer("filter", "dplyr")

```


```{r prepData}
outdir <- tempdir()
skylinePRMSampleData <- LFQService::skylinePRMSampleData_A$data

skylineconfig <-
  create_config_Skyline(isotopeLabel = "Isotope.Label.Type",
                             ident_qValue = "Detection.Q.Value")
skylineconfig$table$factors[["Time"]] = "Sampling.Time.Point"
resData <- setup_analysis(skylinePRMSampleData, skylineconfig)

```

Reorder factors for improved display.

```{r reorderFactors}
xx <- unique(resData$Time)
xxord <- order(as.numeric(gsub("T", "", xx)))

resData$Time <-
  parse_factor(resData$Time, unique(resData$Time)[xxord])
resData$Area[resData$Area == 0] <- NA

```


# Generate overview plots

```{r overviewPlot}
proteinIDsymbol <- sym(names(skylineconfig$table$hierarchy)[1])
xnested <-
  resData %>% dplyr::group_by(UQ(proteinIDsymbol)) %>% tidyr::nest()
xnested

figs <-
  xnested %>% dplyr::mutate(plot = map2(
    data,
    UQ(proteinIDsymbol) ,
    plot_hierarchies_line,
    skylineconfig
  ))

for (i in 1:nrow(xnested)) {
  plot_hierarchies_line(xnested$data[[i]],xnested[[proteinIDsymbol]][i],skylineconfig)
}

print(figs$plot[[1]])

```

```{r Plot2File ,eval=TRUE}
if (FALSE) {
  pdf(
    file.path(outdir, "allProteinsTransitions.pdf"),
    width = 10,
    height = 10
  )
  invisible(lapply(figs$plot[1:3], print))
  dev.off()
}

```

# Compute protein level intensities using medpolish


```{r transformData}
resDataLog <-
  LFQService::transform_work_intensity(resData , skylineconfig, log2)

figs3 <-
  intensity_summary_by_hkeys(resDataLog, skylineconfig, medpolishPly)
figs3 <- figs3("nested")
```


```{r plotData}

figs3 <-
  figs3$xnested %>% dplyr::mutate(plotlog = map2(
    data,
    UQ(proteinIDsymbol) ,
    plot_hierarchies_line,
    skylineconfig
  ))
plot_hierarchies_add_quantline(figs3$plotlog[[1]],
                               figs3$medpolishPly[[1]],
                               "medpolish",
                               skylineconfig)

figs3 <-
  figs3 %>% dplyr::mutate(
    figsMed = map2(
      plotlog,
      medpolishPly,
      plot_hierarchies_add_quantline,
      "medpolish" ,
      skylineconfig
    )
  )
print(figs3$figsMed[[1]])

```

```{r plotAllToFile2, eval=TRUE}
if (FALSE) {
pdf(file.path(outdir , "allProteinsWithMed.pdf"),
    width = 10,
    height = 10)
invisible(lapply(figs3$figsMed[1:3], print))
dev.off()
}

```


```{r getProtQuants}
table <- skylineconfig$table
protIntensity <-
  figs3 %>% select(table$hierarchyKeys()[1], medpolishPly) %>%
  tidyr::unnest(cols = "medpolishPly")

```

## Normalize Protein instensities using CiRT peptides 

```{r plotProtQuants}
CiRT <-
  protIntensity %>% dplyr::filter(protein_Id == "CiRT standards")
# Normalize py CiRT protein
proteinIntensity <- protIntensity %>%
  dplyr::inner_join(CiRT,
                    by = dplyr::setdiff(names(protIntensity),
                                        c("protein_Id", "medpolish")),
                    suffix = c("", ".CiRT")) %>%
  dplyr::mutate(log2Med_log2MedCiRT = medpolish - medpolish.CiRT)


p <-
  ggplot(
    proteinIntensity,
    aes(
      x = sampleName ,
      y = log2Med_log2MedCiRT,
      group = protein_Id,
      color = protein_Id
    )
  ) +
  geom_line() +
  facet_grid( ~ Time, scales = "free_x") + theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "top") +
  ylab(expression(log[2](frac(P, CiRT))))
p

```



```{r plotAndWrite, eval=TRUE}
if (FALSE) {
  pdf(file.path(outdir, "allProteinsOnePlot.pdf"))
  print(p)
  dev.off()
  write_tsv(proteinIntensity, path = file.path(outdir, "ProteinQuants.tsv"))
}

```


```{r plotConditionAverages}
protRez3 <-
  proteinIntensity %>% dplyr::group_by(protein_Id) %>% tidyr::nest()

tmp <-
  function(x) {
    anova(lm(log2Med_log2MedCiRT ~ Time, data = x))
  }

protRez3 <- protRez3 %>% dplyr::mutate(anova = map(data, tmp))
protRez3 <- protRez3 %>% dplyr::mutate(ba = map(anova, broom::tidy))

plotProt <- function(data, title) {
  ggplot(data, aes(x = Time, y = log2Med_log2MedCiRT)) +
    geom_point(fill = "red",
               color = 2,
               size = 2) +
    stat_summary(fun = mean,
                 geom = "line",
                 aes(group = 1),
                 col = "blue") +
    stat_summary(fun = mean,
                 geom = "point",
                 col = "blue") + ggtitle(title) +
    theme_classic() + ylab(expression(log[2](frac(P, CiRT))))
}

plotProt(protRez3$data[[3]], protRez3$protein_Id[[3]])

```

```{r printAllAverages, eval=FALSE}
protRez3 <-
  protRez3 %>% dplyr::mutate(plot = map2(data, protein_Id, plotProt))

pdf(file.path(outdir, "allProtFigsNorm.pdf"))
invisible(lapply(protRez3$plot[1:3], print))
dev.off()

```


```{r plotProteinMedians}
plotProtMedian <- function(data, title) {
  ggplot(data, aes(x = Time, y = log2Med_log2MedCiRT)) +
    geom_point(fill = "red",
               color = 2,
               size = 2) +
    stat_summary(fun = median,
                 geom = "line",
                 aes(group = 1),
                 col = "blue") +
    stat_summary(fun = median,
                 geom = "point",
                 col = "blue") + ggtitle(title) +
    theme_classic() + ylab(expression(log[2](frac(P, CiRT))))
}


protRez3 <-
  protRez3 %>% dplyr::mutate(plotMedian = map2(data, protein_Id, plotProtMedian))
protRez3$plotMedian[1]

```

```{r eval=FALSE}
pdf(file.path(outdir, "allProtFigsNormMedian.pdf"))
invisible(lapply(protRez3$plotMedian[1:3], print))
dev.off()

```

