---
title: "Analyse correlation among precursors"
author: "Functional Genomics Center Zurich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
vignette: >
  %\VignetteIndexEntry{Analyse correlations among precursors}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  fig.height = 10
)

```


```{r}
rm(list=ls())
library(conflicted)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(LFQService)
```


# Setup Data

```{r}
config <- createSpectronautPeptideConfiguration()
config$table$factors[["coding"]] = "coding"
config$table$factors[["sex"]] = "sex"
config$table$factors[["age"]] = "age"
config$table$factors[["Sample_id"]] = "Sample.Name"

x <- R6extractValues(config)
```


```{r include=FALSE, eval=FALSE, echo=FALSE}
if(0){
not <- c("R.Condition", "R.Fraction", "R.Label", "R.Replicate", "PG.ProteinGroups" ,"PG.Cscore","PG.Qvalue","PG.RunEvidenceCount",
"PEP.GroupingKey", "PEP.GroupingKeyType",   "PEP.IsProteotypic",               "PEP.NrOfMissedCleavages",
"PEP.Rank",   "PEP.RunEvidenceCount",            "PEP.UsedForProteinGroupQuantity",
"EG.iRTPredicted",                 "EG.IsDecoy" ,"EG.ModifiedPeptide",
"EG.UserGroup",                    "EG.Workflow",
"EG.IsUserPeak",                   "EG.IsVerified",  "EG.iRTEmpirical",
"EG.MeanApexRT",                   "EG.RTPredicted",                  "EG.AvgProfileQvalue",             "EG.MaxProfileQvalue",
"EG.MinProfileQvalue",             "EG.PercentileQvalue",             "EG.ReferenceQuantity..Settings.", "EG.TargetQuantity..Settings.",
"FG.PrecMz",                       "FG.PrecMzCalibrated",             "FG.ShapeQualityScore",
"Tube.Id","Extract.Name" ,"Species" ,"Condition","Resource_id", "EG.good")



longFormat <- readr::read_tsv("D:/projects/p2244_ProjectOrder_3687/inputData/preprocessing/withAnnotation_3687_DB_WithIsoforms.txt")
colnames(longFormat) <- make.names(colnames(longFormat))
longFormat <- longFormat %>% select(which(!colnames(longFormat) %in% not))
spectronautDIAData250 <- longFormat
#usethis::use_data(spectronautDIAData250,overwrite = TRUE)
}
```

```{r}
longFormat <- LFQService::spectronautDIAData250
"PEP.StrippedSequence" %in% colnames(longFormat)
longFormat$Isotope.Label <- "Light"

config_tmp <- config$clone(deep=TRUE)
longNoDecoy <- setup_analysis(longFormat, config)

```

## QValue Summaries


```{r}
data <- longNoDecoy
longNoDecoy <- removeLarge_Q_Values(longNoDecoy, config)

longQSummaries <- summariseQValues(longNoDecoy, config)
knitr::kable(head(LFQService::interaction_missing_stats(longQSummaries, config)))
```


## Filter by NA's

```{r}
knitr::kable(LFQService::hierarchyCounts(longQSummaries, config))
```

```{r}
qvalFilt <- longQSummaries %>% 
  filter_at( "srm_QValueMin" , all_vars(. < config$parameter$qVal_experiment_threshold )   )
LFQService::hierarchyCounts(qvalFilt, config)
longQNASummaries <- rankPrecursorsByNAs(qvalFilt, config)
longQNASummaries <- longQNASummaries %>% dplyr::filter(srm_NrNotNAs > 20)
knitr::kable(LFQService::hierarchyCounts(longQNASummaries, config))
```


```{r}
res <- plot_heatmap_cor(longQNASummaries, config)
print(res)
```


# Remove single hit wonders

```{r}
xx <- nr_B_in_A(longQNASummaries,config$table$hierarchyKeys()[1], config$table$hierarchyKeys()[2], FALSE)
longQNASummaries <- nr_B_in_A(longQNASummaries,config$table$hierarchyKeys()[1], config$table$hierarchyKeys()[2])

qvalFiltV <- dplyr::filter(longQNASummaries, nr_peptide_Id_by_protein_Id > 1)
knitr::kable(hierarchyCounts(qvalFiltV,config))

```


# Correlation Filtering

```{r markdecorellated}
#config$table$popWorkIntensity()
qvalFiltV <- transform_work_intensity(qvalFiltV, config, log2)
xx <- markDecorrelated(qvalFiltV, config, minCorrelation = 0.5 )
mean(xx$srm_decorelated)
```

```{r shownotcorrelated}
nested <- xx %>% group_by_at(config$table$hkeysLevel()) %>% tidyr::nest()

plot_hierarchies_line(nested$data[[1]], nested$protein_Id[[1]], config) + 
  geom_line(aes_string(linetype = "srm_decorelated"), lwd=0.2) 
plot_hierarchies_line(nested$data[[2]], nested$protein_Id[[2]], config) + 
  geom_line(aes_string(linetype = "srm_decorelated"))
plot_hierarchies_line(nested$data[[3]], nested$protein_Id[[3]], config) + 
  geom_line(aes_string(linetype = "srm_decorelated"))
```


```{r summarizeDataAfterCorrelationRemoval}
knitr::kable(hierarchyCounts(xx, config))
qvalFiltCorr <- dplyr::filter(xx, srm_decorelated == FALSE)
knitr::kable(hierarchyCounts(qvalFiltCorr, config))
```

```{r clusterOfCorrelatedData}
print(plot_heatmap_cor(qvalFiltCorr, config))
```

### Rank precursors by Intensity

```{r rankprec}
qvalFiltImputed <- impute_correlationBased(qvalFiltCorr, config)
qvalFiltImputed <- rankPrecursorsByIntensity(qvalFiltImputed, config)

```

# Aggregation


```{r aggregate}

mean_na <- function(x){mean(x,na.rm=TRUE)}
proteinIntensities <- aggregateTopNIntensities(qvalFiltImputed,
                                               config,
                                               func = mean_na, N=3)$data

```


```{r doplottingOFProtein}
# nest transtions
xnested <- qvalFiltImputed %>% group_by_at(config$table$hierarchyKeys()[1]) %>% tidyr::nest()


#plot_hierarchies_line(xnested$data[[1]], xnested$protein_Id[1],config)
#plot_hierarchies_line(xnested$data[[3]], xnested$protein_Id[3],config)
#plot_hierarchies_line(xnested$data[[4]], xnested$protein_Id[4],config)
# nest protein quants.
figs3 <- xnested %>% dplyr::mutate(plotlog = map2(data, UQ(sym(config$table$hierarchyKeys()[1])),plot_hierarchies_line, config))

ff <- proteinIntensities %>% 
  group_by_at(config$table$hierarchyKeys()[1]) %>% 
  tidyr::nest(.key = "topNIntensity")

figs4 <- dplyr::inner_join(figs3,ff)

plot_hierarchies_add_quantline(figs4$plotlog[[1]], figs4$topNIntensity[[1]], "srm_mean_na_3", config)
plot_hierarchies_add_quantline(figs4$plotlog[[2]], figs4$topNIntensity[[2]], "srm_mean_na_3", config)
plot_hierarchies_add_quantline(figs4$plotlog[[3]], figs4$topNIntensity[[3]], "srm_mean_na_3", config)


proteinsWide <- tidyr::spread(proteinIntensities, sampleName,srm_mean_na_3)

#quantable::simpleheatmap(t(scale(t(log2(1+proteinsWide[2:ncol(proteinsWide)])))), margins = c(16,5))

nrPep <- qvalFiltImputed %>% select(config$table$hierarchyKeys()[1], nr_peptide_Id_by_protein_Id) %>% distinct()
xx <- dplyr::inner_join(nrPep,proteinsWide)
#readr::write_csv(xx, path="output/proteinQuantsTidy.txt")

```


