---
title: "Example of data preprocessing of Heavy Light data"
author: "Functional Genomics Center Zurich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
vignette: >
  %\VignetteIndexEntry{Example of data preprocessing for HL experiment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
echo = TRUE,
message = FALSE,
warning = FALSE,
fig.width = 10,
fig.height = 10
)
```

```{r}
rm(list=ls())
library(conflicted)
library(tidyverse)
library(LFQService)
```



```{r}
outdir <- tempdir()
```

# Setting up the configuration

```{r}
allDataM <- LFQService::skylineSRM_HL_data

skylineconfig <- createSkylineConfiguration(isotopeLabel="Isotope.Label", ident_qValue="annotation_QValue")
skylineconfig$table$factors[["treatment_c"]] <- "Condition2"
skylineconfig$table$factors[["time_c"]] <- "time"
skylineconfig$parameter$is_intensity_transformed = FALSE

resData <- setup_analysis(allDataM, skylineconfig)

resData$Area[resData$Area == 0] <- NA

tt <- R6extractValues(skylineconfig)
```

```{r eval=FALSE}
yaml::write_yaml(tt, file=file.path(outdir,"testSkyline.yml"))
```


```{r fig.cap="transitions in one plot."}
proteinIDsymbol <- sym(skylineconfig$table$hierarchyKeys()[1])

xnested <- resData %>% dplyr::group_by(UQ(proteinIDsymbol)) %>% tidyr::nest()
plot_hierarchies_line(xnested$data[[2]], xnested$protein_Id[[2]], skylineconfig)
```

```{r fig.cap="transitions in separate plot."}
plot_hierarchies_line(xnested$data[[3]], xnested$protein_Id[[3]], skylineconfig, separate = TRUE)
```

\clearpage


## Example how to report all proteins.

```{r eval=FALSE}
figs <- xnested %>%
  dplyr::mutate(plot = map2(data, UQ(proteinIDsymbol) , plot_hierarchies_line, skylineconfig, separate = TRUE))

pdf(file.path(outdir,"allProteins.pdf"), width = 10, height = 10)
invisible(lapply(figs$plot[1:3], print))
dev.off()
```

# Rendering the SRMReport

```{r eval = FALSE}
rmarkdown::render("tr_srm_summary_HL.Rmd",
                  params = list(data=resData, configuration = skylineconfig),
                  envir = new.env(),
                  output_file = "SRMReport.pdf")
```

# Computing L to Heavy fold changes

```{r}
HLData <- spreadValueVarsIsotopeLabel(resData, skylineconfig)
HLData <- HLData %>% dplyr::mutate(log2L_log2H = log2(light_Area)- log2(heavy_Area))
HLData$Isotope.Label <- "L/H"

skylineconfigHL <- skylineconfig
skylineconfigHL$table$workIntensity = "log2L_log2H"
skylineconfigHL$parameter$is_intensity_transformed = TRUE
skylineconfigHL$table$isotopeLabel

xnested <- HLData %>% dplyr::group_by(UQ(proteinIDsymbol)) %>% tidyr::nest()
skylineconfigHL$table$getWorkIntensity()
```

## Plot heavy to light ratio

```{r}
plot_hierarchies_line(xnested$data[[2]], xnested$protein_Id[[2]], skylineconfigHL)
HLfigs <- xnested %>% dplyr::mutate(plot = map2(data, UQ(proteinIDsymbol) , plot_hierarchies_line, skylineconfig))

```


```{r eval=FALSE}

pdf(file.path(outdir,"allHLProteins.pdf"), width = 10, height = 10)
invisible(lapply(HLfigs$plot[1:3], print))
dev.off()
```

# Compute a protein level summary

```{r}
skylineconfigHL$table$hkeysLevel()

HLfigs3 <- LFQService::applyToHierarchyBySample(HLData, skylineconfigHL, medpolishPly)

HLfigs3 <- dplyr::inner_join(HLfigs3,HLfigs, by=skylineconfigHL$table$hierarchyKeys()[1])
p <- plot_hierarchies_line(xnested$data[[2]], xnested$protein_Id[[2]], skylineconfigHL) %>%
  plot_hierarchies_add_quantline(HLfigs3$medpolishPly[[2]],"medpolish", skylineconfigHL)
p
```

```{r eval=FALSE}

HLfigs3 <- HLfigs3 %>% dplyr::mutate(figsMed = map2(plot, medpolishPly, plot_hierarchies_add_quantline, "medpolish", skylineconfig))

pdf(file.path(outdir,"allProteinsWithMed.pdf"), width = 10, height = 10)
invisible(lapply(HLfigs3$figsMed[2:5], print))
dev.off()
```

# Get Protein intensities

```{r fig.cap="Plot protein intensities"}
prots <- HLfigs3 %>% dplyr::select(as.character(proteinIDsymbol),  medpolishPly) %>% 
  tidyr::unnest()
write_tsv(prots, path = file.path(outdir,"proteins.tsv"))

ggplot(prots, aes(x=time_c, y=medpolish, group=treatment_c, color=treatment_c )) +
  geom_point() +
  geom_line() +
  facet_wrap(~protein_Id) +
  theme_classic()

```


```{r fig.cap="Plot protein intensities"}
ggplot(prots, aes(x=time_c, y=medpolish, group=treatment_c, color=treatment_c )) +
  geom_point() +
  geom_line() +
  facet_wrap(~protein_Id, scales="free_y" ) +
  theme_classic()
```




