---
title: "Supplement - Data preprocessing of SRM Heavy Light data"
author: "Functional Genomics Center Zurich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
vignette: >
  %\VignetteIndexEntry{Supplement - Data preprocessing of SRM Heavy Light data}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
echo = TRUE,
message = FALSE,
warning = FALSE,
fig.width = 10,
fig.height = 10
)
```

```{r loadLibs}
rm(list = ls())
library(conflicted)
library(tidyverse)
library(prolfqua)
```



```{r gettmpdir}
outdir <- tempdir()
```

# Setting up the configuration

```{r loadDataCreateConfig}
allDataM <- prolfqua::data_skylineSRM_HL_A$data


skylineconfig <- create_config_Skyline(isotopeLabel = "Isotope.Label",
                                            ident_qValue = "annotation_QValue")
skylineconfig$table$factors[["treatment_c"]] <- "Condition2"
skylineconfig$table$factors[["time_c"]] <- "time"
skylineconfig$table$is_intensity_transformed = FALSE

resData <- setup_analysis(allDataM, skylineconfig)

resData$Area[resData$Area == 0] <- NA

tt <- R6extractValues(skylineconfig)
```

```{r writeYaml, eval=FALSE}
yaml::write_yaml(tt, file=file.path(outdir,"testSkyline.yml"))
```


```{r plotHierarchies, fig.cap="transitions in one plot."}
proteinIDsymbol <- sym(skylineconfig$table$hierarchyKeys()[1])

xnested <- resData %>% dplyr::group_by(UQ(proteinIDsymbol)) %>% tidyr::nest()
plot_hierarchies_line(xnested$data[[2]],
                      xnested$protein_Id[[2]],
                      skylineconfig)

```


```{r plotHierarchies2, fig.cap="transitions in separate plot."}
plot_hierarchies_line(xnested$data[[3]],
                      xnested$protein_Id[[3]],
                      skylineconfig,
                      separate = TRUE)
```

\clearpage


## Example how to report all proteins.

```{r  printAllproteins, eval=FALSE}
figs <- xnested %>%
  dplyr::mutate(plot = map2(data, UQ(proteinIDsymbol),
                            plot_hierarchies_line, skylineconfig, separate = TRUE))

pdf(file.path(outdir,"allProteins.pdf"), width = 10, height = 10)
invisible(lapply(figs$plot[1:3], print))
dev.off()
```

# Rendering the SRMReport

```{r renderReports ,eval = FALSE}
rmarkdown::render("tr_srm_summary_HL.Rmd",
                  params = list(data=resData, configuration = skylineconfig),
                  envir = new.env(),
                  output_file = "SRMReport.pdf")
```

# Computing L to Heavy fold changes

```{r spearateHeavyAndLight}
HLData <- spreadValueVarsIsotopeLabel(resData, skylineconfig)
HLData <- HLData %>% dplyr::mutate(log2L_log2H = log2(light_Area) - log2(heavy_Area))
HLData$Isotope.Label <- "L/H"

skylineconfigHL <- skylineconfig
skylineconfigHL$table$workIntensity = "log2L_log2H"
skylineconfigHL$table$is_intensity_transformed = TRUE
skylineconfigHL$table$isotopeLabel

xnested <- HLData %>% dplyr::group_by(UQ(proteinIDsymbol)) %>% tidyr::nest()
skylineconfigHL$table$getWorkIntensity()

```

## Plot heavy to light ratio

```{r PlotHierarchiesLight}
plot_hierarchies_line(xnested$data[[2]], xnested$protein_Id[[2]], skylineconfigHL)
HLfigs <- xnested %>% dplyr::mutate(plot = map2(data, UQ(proteinIDsymbol) , plot_hierarchies_line, skylineconfig))

```


```{r PlotAllProteins, eval=TRUE}

#pdf(file.path(outdir,"allHLProteins.pdf"), width = 10, height = 10)
invisible(lapply(HLfigs$plot[1:3], print))
#dev.off()
```

# Compute a protein level summary

```{r summarizeProteinMedpolish}
skylineconfigHL$table$hkeysDepth()

HLfigs3 <- prolfqua::intensity_summary_by_hkeys(HLData, skylineconfigHL, medpolishPly)
HLfigs3 <- HLfigs3("nested")
HLfigs3 <- dplyr::inner_join(HLfigs3$xnested, HLfigs, by = skylineconfigHL$table$hkeysDepth())

p <- plot_hierarchies_line(xnested$data[[2]], xnested$protein_Id[[2]], skylineconfigHL) %>%
  plot_hierarchies_add_quantline(HLfigs3$medpolishPly[[2]],"medpolish", skylineconfigHL)
p

```

```{r writeSummaries ,eval=TRUE}

HLfigs3 <- HLfigs3 %>%
  dplyr::mutate(figsMed = map2(plot, medpolishPly, plot_hierarchies_add_quantline, "medpolish", skylineconfig))

#pdf(file.path(outdir,"allProteinsWithMed.pdf"), width = 10, height = 10)+
invisible(lapply(HLfigs3$figsMed[2:5], print))
#dev.off()
```

# Get Protein intensities

```{r plotProteinIntensities, fig.cap="Plot protein intensities"}
prots <- HLfigs3 %>% dplyr::select(as.character(proteinIDsymbol),  medpolishPly) %>% 
  tidyr::unnest(cols = "medpolishPly")

ggplot(prots, aes(x = time_c, y = medpolish, group = treatment_c, color = treatment_c )) +
  geom_point() +
  geom_line() +
  facet_wrap(~protein_Id) +
  theme_classic()

```


```{r plotProteinIntensitiesFreeY, fig.cap="Plot protein intensities"}
ggplot(prots, aes(x = time_c, y = medpolish, group = treatment_c, color = treatment_c )) +
  geom_point() +
  geom_line() +
  facet_wrap(~protein_Id, scales = "free_y" ) +
  theme_classic()
```




