---
title: "Supplement - Summarize SRM Peptide Level Measurements"
author: "WEW@FGCZ.ETHZ.CH"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
params:
  configuration:  !r parse(text="data('data_skylinePRMSample_A');data_skylinePRMSample_A$config_f()")
  data: !r parse(text = "data('data_skylinePRMSample_A'); data_skylinePRMSample_A$analysis(data_skylinePRMSample_A$data, data_skylinePRMSample_A$config_f() ) ")
vignette: >
  %\VignetteIndexEntry{Supplement - Summarize Peptide Level Measurements}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r setup, include=FALSE}
library(prolfqua)
conflicted::conflict_prefer("filter", "dplyr")

knitr::opts_chunk$set(
echo = TRUE,
message = FALSE,
warning = FALSE,
fig.width = 10,
fig.height = 10
)

data <- eval(params$data)
configuration <- eval(params$configuration)

```

## Summarize levels

```{r hierarchy_counts}

x <- hierarchy_counts( data , configuration )
knitr::kable(data.frame(NR = x), caption = "summary")

```


```{r missingFigIntensityHistorgram, fig.cap="histogram of mean condition intensities per transition"}

#interaction_missing_stats(data, configuration)
#interaction_missing_stats(data, configuration)

missigness_histogram(data, configuration)

```


```{r missingFigBarplot, fig.cap = "nr of missing"}
xx <- missingness_per_condition(data, configuration)
xx$figure
```



```{r missingFigBarplotCumsum, fig.cap="cumulative sum of missing"}
xx <- missingness_per_condition_cumsum(data, configuration)
xx$figure
```
