---
title: "Impute"
output: html_document
date: "2024-04-22"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


alternatively use

```{r lookAtSummarizeStats}
library(tidyverse)

dd <- prolfqua::sim_lfq_data_protein_config(Nprot = 100,weight_missing = 2)
dd$data$abundance |> is.na() |> sum()

Contrasts <- c("dilution.b-a" = "group_A - group_B", "dilution.c-e" = "group_A - group_Ctrl")
mh1 <- prolfqua::MissingHelpers$new(dd$data, dd$config, prob = 0.5,weighted = TRUE)
imputed <- mh1$get_contrasts(Contrasts = Contrasts)
mh2 <- prolfqua::MissingHelpers$new(dd$data, dd$config, prob = 0.5,weighted = FALSE)
imputed2 <- mh2$get_contrasts(Contrasts = Contrasts)
plot(imputed$estimate, imputed2$estimate)
abline(0 , 1 , col=2 , lwd=2)


plot( imputed$estimate, -log10(imputed$FDR), pch = "*" )
points(imputed2$estimate, -log10(imputed2$FDR), col = 2, pch = "x")

```




## Look at current implementation




```{r currentImpl}
library(prolfqua)

#dd <- prolfqua::sim_lfq_data_protein_config(Nprot = 100,weight_missing = 2)
#dd$data$abundance |> is.na() |> sum()

protIntensity <- dd$data
config <- dd$config
lProt <- LFQData$new(protIntensity, config)
lProt$rename_response("transformedIntensity")
csi <- ContrastsMissing$new(lProt, contrasts = Contrasts)
csi$get_contrast_sides()
xd <- csi$get_contrasts()


xxd <- inner_join(xd,imputed2, by = c("contrast", "protein_Id"), suffix = c(".old",".new"))
plot(xxd$diff, xxd$estimate)

dev <- xxd |> dplyr::filter(abs(FDR.old - FDR.new) > 0) 
plot(xxd$p.value.old, xxd$p.value.new)
plot(xxd$diff, xxd$estimate)

xxd2 <- inner_join(xd,imputed, by = c("contrast", "protein_Id"))
plot(xxd2$diff, xxd2$estimate)

plot(xxd2$FDR.x, xxd2$FDR.y)
hist(xxd2$p.value.x)
hist(xxd2$p.value.y)

```


```{r}
xx <- prolfqua:::get_impute_contrasts_V1(lProt, Contrasts, all = TRUE)

dim(xx)
xx <- xx |> arrange(contrast, protein_Id)
imputed2 <- imputed2 |> arrange(contrast, protein_Id)
plot(xx$estimate_median, imputed2$estimate)

plot(xx$p.value, imputed2$p.value)
plot(xx$df, imputed2$df)

plot(xx$sd - imputed2$sd)
tt <- which(abs(xx$sdT -  imputed2$sdT) >0)
xx$df |> table()
imputed2$df |> table()


```

## modelling with linear models


Model with missing data

```{r lmModel}
modelName <- "f_condtion_r_peptide"
formula_Protein <-
  strategy_lm("abundance  ~ group_",
              model_name = modelName)


mod <- prolfqua::build_model(
  dd$data,
  formula_Protein,
  modelName = modelName,
  subject_Id = dd$config$table$hierarchy_keys_depth())
mod$modelDF
mod$modelDF$nrcoeff_not_NA |> table()


mod$modelDF$isSingular |> table()
mod$modelDF |> nrow()
mod$get_anova()
model_summary(mod)

maxcoef <- max(mod$modelDF$nrcoeff_not_NA, na.rm = TRUE)
goodmods <- mod$modelDF |> dplyr::filter(isSingular == FALSE, exists_lmer == TRUE, nrcoeff_not_NA == maxcoef)

dim(goodmods)
xx <- lapply(goodmods$linear_model, vcov)
nr <- sapply(xx, nrow)
nr |> table()
nr <- sapply(xx, ncol)
nr |> table()
sum_matrix <- Reduce(`+`, xx)
sum_matrix/length(xx)


```

Model with lod imputation

```{r lmod2}
loddata <- dd$data
loddata <- loddata |> dplyr::mutate(abundance = ifelse(is.na(abundance), LOD, abundance))
modI <- prolfqua::build_model(
  loddata,
  formula_Protein,
  modelName = modelName,
  subject_Id = dd$config$table$hierarchy_keys_depth())


modI$modelDF$nrcoeff_not_NA |> table()
modI$modelDF$isSingular |> table()
modI$modelDF |> nrow()

allModels <- modI$modelDF$linear_model

xx <- lapply(allModels, vcov)
sum_matrix <- Reduce(`+`, xx)
sum_matrix/length(xx)


```


```{r}
m <- (modI$modelDF$linear_model[[1]])
df.residual(m)
sigma(m)
vcov(m)


```
