---
title: "Summarize Peptide Level Measurements"
author: "WEW@FGCZ.ETHZ.CH"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
params:
  configuration:  !r quote(LFQServiceData::skylineconfig)
  data: !r quote(LFQServiceData::sample_analysis)
vignette: >
  %\VignetteIndexEntry{Summarize Peptide Level Measurements}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



```{r setup, include=FALSE}
library(tidyverse)
library(LFQService)


knitr::opts_chunk$set(echo = FALSE, message=FALSE)
data <- eval(params$data)
configuration <- eval(params$configuration)

```

## Summarize levels

```{r hierarchy_counts}

x <- hierarchy_counts( data , configuration )
knitr::kable(data.frame(NR = x), caption="summary")

```


```{r proteinSummaries}

x2 <- summarizeProteins(data, configuration)
x3 <- summarize_hierarchy(data, configuration)
tmp <- dplyr::inner_join(x3, x2)
tmp <- tmp %>% select(-c(starts_with("min"), starts_with("max")))
knitr::kable(tmp, caption = "Protein Summaries")

```


```{r missingFigIntensityHistorgram, fig.cap="histogram of mean condition intensities per transition"}

#interaction_missing_stats(data, configuration)
#interaction_missing_stats(data, configuration)

missigness_histogram(data, configuration)

```


```{r missingFigBarplot, fig.cap = "nr of missing"}
xx <- missingness_per_condition(data, configuration)
xx$figure
```



```{r missingFigBarplotCumsum, fig.cap="cumulative sum of missing"}
xx <- missingness_per_condition_cumsum(data, configuration)
xx$figure
```
