---
title: "Analyse correlation among precursors"
author: "Functional Genomics Center Zurich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
vignette: >
  %\VignetteIndexEntry{Analyse correlations among precursors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

  
```{r setup, include=FALSE}
knitr::opts_chunk$set(
echo = FALSE,
message = FALSE,
warning = FALSE,
fig.width = 10,
fig.height = 10
)

```



```{r}
rm(list=ls())
library(conflicted)
library(tidyverse)
library(dplyr)
library(ggplot2)

rm(list=ls())
library(SRMService)
config <- createSpectronautPeptideConfiguration()
config$table$factors[["coding"]] = "coding"
config$table$factors[["sex"]] = "sex"
config$table$factors[["age"]] = "age"
config$table$factors[["Sample_id"]] = "Sample.Name"

x <- R6extractValues(config)
```


```{r include=FALSE, eval=FALSE}
if(0){
  not <- c("R.Condition", "R.Fraction", "R.Label", "R.Replicate", "PG.ProteinGroups" ,"PG.Cscore","PG.Qvalue","PG.RunEvidenceCount",
           "PEP.GroupingKey", "PEP.GroupingKeyType",   "PEP.IsProteotypic",               "PEP.NrOfMissedCleavages",
           "PEP.Rank",   "PEP.RunEvidenceCount",            "PEP.UsedForProteinGroupQuantity",
           "EG.iRTPredicted",                 "EG.IsDecoy" ,"EG.ModifiedPeptide",
           "EG.UserGroup",                    "EG.Workflow",
           "EG.IsUserPeak",                   "EG.IsVerified",  "EG.iRTEmpirical",
           "EG.MeanApexRT",                   "EG.RTPredicted",                  "EG.AvgProfileQvalue",             "EG.MaxProfileQvalue",
           "EG.MinProfileQvalue",             "EG.PercentileQvalue",             "EG.ReferenceQuantity..Settings.", "EG.TargetQuantity..Settings.",
           "FG.PrecMz",                       "FG.PrecMzCalibrated",             "FG.ShapeQualityScore",
           "Tube.Id","Extract.Name" ,"Species" ,"Condition","Resource_id", "EG.good")
  
  
  
  longFormat <- readr::read_tsv("D:/projects/p2244_ProjectOrder_3687/inputData/preprocessing/withAnnotation_3687_DB_WithIsoforms.txt")
  colnames(longFormat) <- make.names(colnames(longFormat))
  longFormat <- longFormat %>% select(which(!colnames(longFormat) %in% not))
  spectronautDIAData250 <- longFormat
  usethis::use_data(spectronautDIAData250,overwrite = TRUE)
}
```

```{r}
longFormat <- SRMService::spectronautDIAData250
"PEP.StrippedSequence" %in% colnames(longFormat)
longFormat$Isotope.Label <- "Light"

config_tmp <- config$clone(deep=TRUE)
longNoDecoy <- setup_analysis(longFormat, config)

```

## QValue Summaries


```{r}
data <- longNoDecoy
longNoDecoy <- removeLarge_Q_Values(longNoDecoy, config)
longQSummaries <- summariseQValues(longNoDecoy, config)
SRMService::getMissingStats(longQSummaries, config)

```


## Filter by NA's

```{r}
SRMService::hierarchyCounts(longQSummaries, config)
qvalFilt <- longQSummaries %>% filter_at( "srm_QValueMin" , all_vars(. < config$parameter$qValThreshold )   )
SRMService::hierarchyCounts(qvalFilt, config)
longQNASummaries <- rankPrecursorsByNAs(qvalFilt, config)
longQNASummaries <- longQNASummaries %>% dplyr::filter(srm_NrNotNAs > 20)
SRMService::hierarchyCounts(longQNASummaries, config)
```


```{r}
tmp <- toWideConfig(longQNASummaries, config, as.matrix = TRUE)
quantable::simpleheatmap(cor(log2(tmp), use="pairwise.complete.obs"), margin=c(15,5))

```


# Remove single hit wonders

```{r}
xx <- nr_B_in_A(longQNASummaries,config$table$hierarchyKeys()[1], config$table$hierarchyKeys()[2], FALSE)
longQNASummaries <- nr_B_in_A(longQNASummaries,config$table$hierarchyKeys()[1], config$table$hierarchyKeys()[2])
qvalFiltV <- dplyr::filter(longQNASummaries, nr_peptide_Id_by_protein_Id > 1)
hierarchyCounts(qvalFiltV,config)

```


# Correlation Filtering

```{r}

qvalFiltV <- transform_work_intensity(qvalFiltV, config, log2)
xx <- markDecorrelated(qvalFiltV, config)
hierarchyCounts(xx, config)
qvalFiltCorr <- dplyr::filter(xx, srm_decorelated == FALSE)
hierarchyCounts(qvalFiltCorr, config)

```



```{r}
intensitiesD <- toWideConfig(qvalFiltCorr, config, as.matrix = TRUE)
bb <- cor( intensitiesD, use="pairwise.complete.obs")
quantable::simpleheatmap(bb, margin=c(15,5))

```

### Rank precursors by Intensity

```{r}
qvalFiltCorr %>% select(protein_Id,precursor_Id, srm_NrNotNAs) %>% distinct()
qvalFiltCorrSI <- rankPrecursorsByIntensity(qvalFiltCorr, config)

config$table$getWorkIntensity()
qvalFiltCorrSI %>% select(protein_Id,precursor_Id, starts_with("srm_")) %>% distinct()

qvalFiltImputed <- impute_correlationBased(qvalFiltCorrSI, config)
qvalFiltImputed %>% select(protein_Id,precursor_Id, starts_with("srm_")) %>% distinct()

```

# Aggregation


```{r}

mean_na <- function(x){mean(x,na.rm=TRUE)}
proteinIntensities <- aggregateTopNIntensities(qvalFiltImputed,config,func = mean_na,N=3)$data

# nest transtions
xnested <- qvalFiltImputed %>% group_by_at(config$table$hierarchyKeys()[1]) %>% nest()
linePlotHierarchy_configuration(xnested$data[[1]], xnested$protein_Id[1],config)
linePlotHierarchy_configuration(xnested$data[[3]], xnested$protein_Id[3],config)
linePlotHierarchy_configuration(xnested$data[[4]], xnested$protein_Id[4],config)

# nest protein quants.
figs3 <- xnested %>% mutate(plotlog = map2(data, UQ(sym(config$table$hierarchyKeys()[1])) ,
                                           linePlotHierarchy_configuration, config))
ff <- proteinIntensities %>% group_by_at(config$table$hierarchyKeys()[1]) %>% nest(.key = "topNIntensity")

figs4 <- inner_join(figs3,ff)

linePlotHierarchy_QuantLine(figs4$plotlog[[1]], figs4$topNIntensity[[1]], "srm_mean_na_3", config)
proteinsWide <- spread(proteinIntensities, sampleName,srm_mean_na_3)

#quantable::simpleheatmap(t(scale(t(log2(1+proteinsWide[2:ncol(proteinsWide)])))), margins = c(16,5))
nrPep <- qvalFiltImputed %>% select(config$table$hierarchyKeys()[1], nr_peptide_Id_by_protein_Id) %>% distinct()
xx <- inner_join(nrPep,proteinsWide)
#readr::write_csv(xx, path="output/proteinQuantsTidy.txt")

```

# Combine all in one function.


