---
title: "Crosstalk"
author: "Witold Wolski"
date: "21 September 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(plotly)
library(crosstalk)

d1 <- data.frame(id = letters, x = rnorm(length(letters)), y=runif(length(letters)))
d2 <- data.frame(id = sample(letters, 1000, replace = TRUE), xx = rnorm(1000), yy = runif(1000)) %>% arrange(id)


prot <- SharedData$new(d1,key = "id",group = "ex1")
pep <- SharedData$new(d2,key = "id", group = "ex1")


p1 <- ggplot(prot, aes(x = x,y = y)) + geom_point()
p2 <- ggplot(pep, aes(x = xx, y= yy)) + geom_point()

pp1 <- ggplotly(p1) %>% add_markers(alpha=0.5) 
pp2 <- ggplotly(p2)

bscols(pp1,pp2)

```

```{r}
library(plotly)
library(crosstalk)
rm(list = ls())
d1 <- data.frame(id = letters, x = rnorm(length(letters)), y=runif(length(letters)))
d1shared <- SharedData$new(d1,key = ~id ,group = "ex1")
d1table <- DT::datatable(d1shared, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))

p1plot <- ggplot(d1shared, aes(x = x,y = y)) + geom_point()
pp1plot_p <- ggplotly(p1plot) 
#pp1plot_p <- plotly::plot_ly(d1shared, x = ~x ,y = ~y) |> add_markers() |> highlight("plotly_click")
#pp2plot_p <- plotly::plot_ly(d1shared, x = ~x ,y = ~y) 
bscols(d1table,pp1plot_p)


```

