#'
#'
#'
.linfct <- function(model, contrast, avg = TRUE) {
  linfct <- linfct_from_model(model, as_list = FALSE)
  linfct <- unique(linfct) # needed for single factor models
  if (avg) {
    namtmp <- paste0("avg_", names(contrast))
    cntr_avg <- paste0("(", gsub(" - ", " + ", contrast), ")/2")
    names(cntr_avg) <- namtmp
    contrast <- c(contrast, cntr_avg)
  }
  linfct_a <- linfct_matrix_contrasts(linfct, contrast)
  return(linfct_a)
}

.filter_fitted_firth_models <- function(model_df) {
  model_df |>
    dplyr::filter(
      .data$has_model_fit,
      !is.na(.data$nr_coef_not_NA),
      !purrr::map_lgl(.data$linear_model, is.character)
    )
}

# Contrasts -----

#' Estimate contrasts using Wald Test
#' @return An R6 class generator.
#' @export
#' @family modelling
#' @examples
#'
#' modi <- sim_build_models_logistf(model = "parallel3", weight_missing = 1)
#' contrasts <- c(Avs = "group_A - group_B", AvsCtrl = "group_A - group_Ctrl")
#'
#' ctr <- ContrastsFirth$new(modi,contrasts)
#' ctr$get_contrast_sides()
#' ctr$get_linfct()
#' ctr$get_contrasts()
#'
#' mod3 <- sim_build_models_logistf(model = "parallel3", weight_missing = 1, peptide=TRUE)
#'
#' ctrpep <- ContrastsFirth$new(mod3,contrasts)
#' ctrpep$get_contrast_sides()
#'
#' ctrpep$get_linfct()
#' ctrpep$get_contrasts()
#' pl <- ctrpep$get_Plotter()
#'
ContrastsFirth <- R6::R6Class(
  "ContrastsFirth",
  inherit = ContrastsInterface,
  public = list(
    #' @field models Model
    models = NULL,
    #' @field contrasts character with contrasts
    contrasts = character(),
    #' @field model_name name of model
    model_name = character(),
    #' @field subject_id name of column containing e.g., protein Id's
    subject_id = character(),
    #' @field p.adjust function to adjust p-values (default prolfqua::adjust_p_values)
    p.adjust = NULL,
    #' @field contrast_result data frame containing results of contrast computation
    contrast_result = NULL,
    #' @description
    #' initialize
    #' create Contrast
    #' @param model a dataframe with a structure similar to that generated by \code{\link{build_model}}
    #' @param contrasts a character vector with contrast specificiation
    #' @param p.adjust function to adjust the p-values
    #' @param model_name name of contrast method, default firth
    initialize = function(model, contrasts, p.adjust = prolfqua::adjust_p_values, model_name = "firth") {
      self$models <- model
      self$contrasts <- contrasts
      self$model_name <- model_name
      self$subject_id <- model$subject_id
      self$p.adjust <- p.adjust
    },
    #' @description
    #' get both sides of contrasts
    get_contrast_sides = function() {
      # extract contrast sides
      tt <- self$contrasts[grep("-", self$contrasts)]
      tt <- tibble(contrast = names(tt), rhs = tt)
      tt <- tt |> mutate(rhs = gsub("[` ]", "", rhs)) |> tidyr::separate(rhs, c("group_1", "group_2"), sep = "-")
      return(tt)
    },
    #' @description
    #' get linear functions from contrasts
    #' @param avg logical TRUE - get also linfct for averages
    #' @return a list with the linfct-annotated model containers
    #'   (\code{models1} / \code{models2}); the shared input model is left
    #'   untouched.
    get_linfct = function(avg = TRUE) {
      linfct_models <- list()
      if (!is.null(self$models$models$models1)) {
        models1 <- self$models$models$models1
        model1_df <- .filter_fitted_firth_models(models1$model_df)
        res1 <- vector(mode = "list", nrow(model1_df))
        pb <- .make_progress(nrow(model1_df), label = "firth linfct single-peptide")
        if (nrow(model1_df) > 0) {
          model <- get_complete_model_fit(model1_df)$linear_model[[1]]
          compmodel <- .linfct(model, self$contrasts, avg = avg)
          max_coef <- max(model1_df$nr_coef_not_NA, na.rm = TRUE)

          for (i in seq_along(model1_df$linear_model)) {
            pb$tick()
            res1[[i]] <- if (model1_df$nr_coef_not_NA[[i]] == max_coef) {
              compmodel
            } else {
              .linfct(model1_df$linear_model[[i]], contrast = self$contrasts, avg = avg)
            }
          }
        }
        model1_df$linfct <- res1
        models1$model_df <- model1_df
        linfct_models$models1 <- models1
      }

      if (!is.null(self$models$models$models2)) {
        models2 <- self$models$models$models2
        model2_df <- .filter_fitted_firth_models(models2$model_df)
        pb <- .make_progress(nrow(model2_df), label = "firth linfct multi-peptide")
        res2 <- vector(mode = "list", nrow(model2_df))
        for (i in seq_along(model2_df$linear_model)) {
          pb$tick()
          res2[[i]] <-
            .linfct(model2_df$linear_model[[i]], contrast = self$contrasts, avg = avg)
        }
        model2_df$linfct <- res2
        models2$model_df <- model2_df
        linfct_models$models2 <- models2
      }
      return(linfct_models)
    },
    #' @description
    #' get table with contrast estimates
    #' @param all should all columns be returned (default FALSE)
    #' @return data.frame with contrasts
    #'
    get_contrasts = function(all = FALSE) {
      if (is.null(self$contrast_result)) {
        message("determine linear functions:")
        linfct_models <- self$get_linfct()
        message("get_contrasts -> contrasts_linfct")
        models1 <- linfct_models$models1
        contrast_result1 <- NULL
        contrast_result2 <- NULL
        if (!is.null(models1)) {
          contrast_result1 <- contrasts_linfct_firth(models1)
          contrast_result1 <- ungroup(contrast_result1)
        }
        models2 <- linfct_models$models2
        if (!is.null(models2)) {
          contrast_result2 <- contrasts_linfct_firth(models2)
          contrast_result2 <- ungroup(contrast_result2)
        }
        contrast_result <- bind_rows(contrast_result2, contrast_result1)
        contrast_result <- dplyr::rename(contrast_result, contrast = lhs, diff = estimate)

        differences <- contrast_result |>
          dplyr::filter(contrast %in% names(self$contrasts))

        avg_abd <- contrast_result |>
          dplyr::select(dplyr::all_of(c(self$subject_id, "contrast", "diff"))) |>
          dplyr::filter(startsWith(contrast, "avg_"))

        avg_abd$contrast <- gsub("^avg_", "", avg_abd$contrast)
        avg_abd <- avg_abd |> dplyr::rename(avgAbd = diff)
        contrast_result <- left_join(differences, avg_abd)

        contrast_result <- self$p.adjust(contrast_result, column = "p.value", group_by_col = "contrast")
        contrast_result <- contrast_result |> relocate("FDR", .after = "diff")
        contrast_result$estimate_type <- "observed"
        contrast_result <- mutate(contrast_result, modelName = self$model_name, .before = 1)
        contrast_result <- dplyr::relocate(contrast_result, "estimate_type", .after = "modelName")
        self$contrast_result <- contrast_result
      }
      res <- if (!all) {
        self$contrast_result |>
          select(-all_of(c("sigma.model", "df.residual.model", "isSingular")))
      } else {
        self$contrast_result
      }

      stopifnot(all(super$column_description()$column_name %in% colnames(res)))
      return(res)
    },
    #' @description
    #' return \code{\link{ContrastsPlotter}}
    #' creates Contrast_Plotter
    #' @param fc_threshold fold change threshold to show in plots
    #' @param fdr_threshold FDR threshold to show in plots
    #' @return \code{\link{ContrastsPlotter}}
    get_Plotter = function(
      fc_threshold = 1,
      fdr_threshold = 0.1
    ) {
      contrast_result <- self$get_contrasts()
      res <- ContrastsPlotter$new(
        contrast_result,
        subject_id = self$subject_id,
        fcthresh = fc_threshold,
        volcano = list(list(score = "p.value", thresh = fdr_threshold), list(score = "FDR", thresh = fdr_threshold)),
        histogram = list(list(score = "p.value", xlim = c(0, 1, 0.05)), list(score = "FDR", xlim = c(0, 1, 0.05))),
        score = list(list(score = "statistic", thresh = 5)),
        modelName = "modelName",
        diff = "diff",
        contrast = "contrast"
      )
      return(res)
    },
    #' @description
    #' convert to wide format
    #' @param columns value column default p.value
    #' @return data.frame
    to_wide = function(columns = c("p.value", "FDR", "statistic")) {
      contrast_minimal <- self$get_contrasts()
      contrasts_wide <- pivot_model_contrasts_to_wide(
        contrast_minimal,
        subject_id = self$subject_id,
        columns = c("diff", columns),
        contrast = "contrast"
      )
      return(contrasts_wide)
    }
  )
)
