.filter_fitted_firth_models <- function(model_df) {
  model_df |>
    dplyr::filter(
      .data$has_model_fit,
      !is.na(.data$nr_coef_not_NA),
      !purrr::map_lgl(.data$linear_model, is.character)
    )
}

# Contrasts -----

#' Estimate contrasts using Wald Test
#' @return An R6 class generator.
#' @export
#' @family modelling
#' @examples
#'
#' modi <- sim_build_models_logistf(model = "parallel3", weight_missing = 1)
#' contrasts <- c(Avs = "group_A - group_B", AvsCtrl = "group_A - group_Ctrl")
#'
#' ctr <- ContrastsFirth$new(modi,contrasts)
#' ctr$get_contrast_sides()
#' ctr$get_linfct()
#' ctr$get_contrasts()
#'
#' mod3 <- sim_build_models_logistf(model = "parallel3", weight_missing = 1, peptide=TRUE)
#'
#' ctrpep <- ContrastsFirth$new(mod3,contrasts)
#' ctrpep$get_contrast_sides()
#'
#' ctrpep$get_linfct()
#' ctrpep$get_contrasts()
#' pl <- ctrpep$get_Plotter()
#'
ContrastsFirth <- R6::R6Class(
  "ContrastsFirth",
  inherit = ContrastsInterface,
  public = list(
    #' @field models Model
    models = NULL,
    #' @field contrasts character with contrasts
    contrasts = character(),
    #' @field model_name name of model
    model_name = character(),
    #' @field subject_id name of column containing e.g., protein Id's
    subject_id = character(),
    #' @field p.adjust function to adjust p-values (default prolfqua::adjust_p_values)
    p.adjust = NULL,
    #' @field contrast_result data frame containing results of contrast computation
    contrast_result = NULL,
    #' @description
    #' initialize
    #' create Contrast
    #' @param model a dataframe with a structure similar to that generated by \code{\link{build_model}}
    #' @param contrasts a character vector with contrast specificiation
    #' @param p.adjust function to adjust the p-values
    #' @param model_name name of contrast method, default firth
    initialize = function(model, contrasts, p.adjust = prolfqua::adjust_p_values, model_name = "firth") {
      self$models <- model
      self$contrasts <- contrasts
      self$model_name <- model_name
      self$subject_id <- model$subject_id
      self$p.adjust <- p.adjust
    },
    #' @description
    #' get both sides of contrasts
    get_contrast_sides = function() {
      parse_contrast_sides(self$contrasts)
    },
    #' @description
    #' get linear functions from contrasts
    #' @param avg logical TRUE - get also linfct for averages
    #' @return a list with the linfct-annotated model containers
    #'   (\code{models1} / \code{models2}); the shared input model is left
    #'   untouched.
    get_linfct = function(avg = TRUE) {
      linfct_models <- list()
      labels <- c(models1 = "firth linfct single-peptide", models2 = "firth linfct multi-peptide")
      for (name in names(labels)) {
        models <- self$models$models[[name]]
        if (!is.null(models)) {
          models$model_df <- .filter_fitted_firth_models(models$model_df)
          # multi-peptide models carry protein-specific peptide coefficients: no shared linfct
          models$model_df$linfct <- .linfct_per_model(
            models$model_df,
            self$contrasts,
            avg,
            labels[[name]],
            reuse_complete = name == "models1"
          )
          linfct_models[[name]] <- models
        }
      }
      return(linfct_models)
    },
    #' @description
    #' get table with contrast estimates
    #' @param all should all columns be returned (default FALSE)
    #' @return data.frame with contrasts
    #'
    get_contrasts = function(all = FALSE) {
      if (is.null(self$contrast_result)) {
        message("determine linear functions:")
        linfct_models <- self$get_linfct()
        message("get_contrasts -> contrasts_linfct")
        # multi-peptide rows first; skip model sets without any fitted model
        fitted <- Filter(function(m) !is.null(m) && nrow(m$model_df) > 0, linfct_models[c("models2", "models1")])
        contrast_result <- bind_rows(lapply(fitted, function(models) {
          contrasts_linfct(
            models$model_df,
            models$model_df$linfct,
            subject_id = self$subject_id,
            contrastfun = function(m, linfct) {
              tryCatch(.compute_contrast(m, linfct, strategy = models$strategy), error = function(e) FALSE)
            }
          )
        }))
        contrast_result <- .finalize_wald_contrasts(contrast_result, self$contrasts, self$subject_id, self$p.adjust)
        self$contrast_result <- .stamp_model_identity(contrast_result, self$model_name, "observed")
      }
      res <- .select_wald_columns(self$contrast_result, all)
      stopifnot(all(super$column_description()$column_name %in% colnames(res)))
      return(res)
    }
  )
)
