
#' writes results of `model_analyse`, anova table and all the coefficients with parameters.
#' @keywords internal
#' @export
model_analyse_summarize_write  <- function(
  modellingResult,
  path,
  all = FALSE){
  message("writing tables into :", path)
  if (all) {
    lfq_write_table(modellingResult$Model_Coeff,
                    path = path,
                    name  = modellingResult$fname_Model_Coeff )
  }
  lfq_write_table(modellingResult$Model_Anova,
                  path = path ,
                  name = modellingResult$fname_Model_Anova )
}


#' summarize - compute anova and extract model coefficients  generated by `model_analyse`
#'
#' @export
#' @keywords internal
#' @examples
#' rm(list = ls())
#' library(LFQService)
#' D <- LFQServiceData::ionstar$normalized()
#' D$data <- dplyr::filter(D$data ,protein_Id %in% sample(protein_Id, 10))
#' modelName <- "f_condtion_r_peptide"
#' formula_randomPeptide <-
#'   make_custom_model_lmer("transformedIntensity  ~ dilution. + (1 | peptide_Id)",
#'    model_name = modelName)
#' pepIntensity <- D$data
#' config <- D$config
#' config$table$hkeysDepth()
#' modellingResult <- LFQService:::model_analyse(
#'  pepIntensity,
#'  formula_randomPeptide,
#'  modelName = modelName,
#'  subject_Id = config$table$hkeysDepth())
#' names(modellingResult)
#' tmp <- model_analyse_summarize(modellingResult$modelProtein,
#' subject_Id = config$table$hkeysDepth(),
#'  modelName = modelName)
#' head(tmp$Model_Coeff)
#' head(tmp$Model_Anova)
model_analyse_summarize <- function(modelProteinF,
                                    subject_Id = "protein_Id",
                                    modelName = "Model"
){
  lmermodel <- "linear_model"

  modelProteinF <- get_complete_model_fit(modelProteinF)
  # modelProteinF <- modelProteinF %>% dplyr::filter(nrcoef == max(nrcoef))

  # Extract coefficients
  .coef_df <-  function(x){
    x <- coef(summary(x));
    x <- data.frame(row.names(x), x);
    return(x)
  }

  Model_Coeff <- modelProteinF %>%
    dplyr::mutate(!!"Coeffs_model" := purrr::map( !!sym(lmermodel),  .coef_df ))

  Model_Coeff <- Model_Coeff %>%
    dplyr::select(!!!syms(subject_Id), !!sym("Coeffs_model"), isSingular, nrcoef)

  # Problem with new version of tidyr.
  #if (FALSE) {
  #  Model_Coeff <-  tidyr::unnest(Model_Coeff, cols = "Coeffs_model")
  #} else {
  Model_Coeff <- tidyr::unnest_legacy(Model_Coeff)
  #}

  # ANOVA
  .anova_df <- function(x){
    x <- anova(x)
    colnames(x) <- make.names(colnames(x))
    x <- data.frame(rownames(x), x)
    return(x)
  }

  Model_Anova <- modelProteinF %>% dplyr::mutate(!!"Anova_model" := purrr::map( !!sym(lmermodel),  .anova_df ))

  Model_Anova <- Model_Anova %>%
    dplyr::select(!!!syms(subject_Id), !!sym("Anova_model"), isSingular, nrcoef)
  Model_Anova <- tidyr::unnest_legacy(Model_Anova)
  #tidyr::unnest(cols = "Anova_model")


  return(list(
    modelName = modelName,
    Model_Coeff = Model_Coeff,
    fname_Model_Coeff =  paste0("Coef_",modelName),
    Model_Anova = Model_Anova,
    fname_Model_Anova =  paste0("ANOVA_",modelName)
  ))
}

#' Model
#' @export
#' @examples
#' rm(list = ls())
#' library(LFQService)
#' library(tidyverse)
#' D <- LFQServiceData::ionstar$normalized()
#' D$data <- dplyr::filter(D$data ,protein_Id %in% sample(protein_Id, 10))
#' modelName <- "f_condtion_r_peptide"
#' formula_randomPeptide <-
#'   make_custom_model_lmer("transformedIntensity  ~ dilution. + (1 | peptide_Id)",
#'    model_name = modelName)
#' pepIntensity <- D$data
#' config <- D$config
#' config$table$hkeysDepth()
#' modellingResult <- LFQService:::model_analyse(
#'  pepIntensity,
#'  formula_randomPeptide,
#'  modelName = modelName,
#'  subject_Id = config$table$hkeysDepth())
#' names(modellingResult)
#'
#' mod <- Model$new(
#'   modelDF = modellingResult$modelProtein,
#'   modelName = modellingResult$modelName,
#'   subject_Id = config$table$hkeysDepth())
#'
#' mod$modelDF
#' mod$get_anova()
#' mod$get_coefficients()
#'
Model <- R6::R6Class(
  "Model",
  public = list(
   #' @field modelDF data.frame with modelling data and model.
   modelDF = NULL,
   modelName = character(),
   subject_Id = character(),
   initialize = function(modelDF, modelName, subject_Id = "protein_Id"){
     self$modelDF = modelDF
     self$modelName = modelName
     self$subject_Id = subject_Id

   },
   get_coefficients = function(){
     lmermodel <- "linear_model"
     modelProteinF <- get_complete_model_fit(self$modelDF)
     # modelProteinF <- modelProteinF %>% dplyr::filter(nrcoef == max(nrcoef))
     # Extract coefficients
     .coef_df <-  function(x){
       x <- coef(summary(x));
       x <- data.frame(row.names(x), x);
       return(x)
     }
     Model_Coeff <- modelProteinF %>%
       dplyr::mutate(!!"Coeffs_model" := purrr::map( !!sym(lmermodel),  .coef_df ))
     Model_Coeff <- Model_Coeff %>%
       dplyr::select(!!!syms(self$subject_Id), !!sym("Coeffs_model"), isSingular, nrcoef)
     return(Model_Coeff)
   },
   get_anova = function(){
     lmermodel <- "linear_model"
     modelProteinF <- get_complete_model_fit(self$modelDF)
     # ANOVA
     .anova_df <- function(x){
       x <- anova(x)
       colnames(x) <- make.names(colnames(x))
       x <- data.frame(rownames(x), x)
       return(x)
     }

     Model_Anova <- modelProteinF %>% dplyr::mutate(!!"Anova_model" := purrr::map( !!sym(lmermodel),  .anova_df ))

     Model_Anova <- Model_Anova %>%
       dplyr::select(!!!syms(self$subject_Id), !!sym("Anova_model"), isSingular, nrcoef)
     Model_Anova <- tidyr::unnest_legacy(Model_Anova)
     #tidyr::unnest(cols = "Anova_model")
     return(Model_Anova)

   },
   coef_histogram = function(){
     Model_Coeff <- self$get_coefficients()
     Model_Coeff <- tidyr::unite(Model_Coeff, "subject_Id", self$subject_Id)
     ## Coef_Histogram
     fname_histogram_coeff_p.values <- paste0("Coef_Histogram_",self$modelName,".pdf")
     histogram_coeff_p.values <- ggplot(data = Model_Coeff, aes(x = Pr...t.., group = row.names.x.)) +
       geom_histogram(breaks = seq(0,1,by = 0.05)) +
       facet_wrap(~row.names.x.)

   },
   coef_volcano = function(){
     Model_Coeff <- self$get_coefficients()

     fname_VolcanoPlot <- paste0("Coef_VolcanoPlot_",self$modelName,".pdf")
     VolcanoPlot <- Model_Coeff %>%
       dplyr::filter(row.names.x. != "(Intercept)") %>%
       LFQService::multigroupVolcano(
         effect = "Estimate",
         p.value = "Pr...t..",
         condition = "row.names.x.",
         label = "subject_Id" ,
         xintercept = c(-1, 1) ,
         colour = "isSingular" )
   },
   coef_pairs = function(){
     Model_Coeff <- self$get_coefficients()
     ## Coef_Pairsplot
     forPairs <- Model_Coeff %>%
       dplyr::select(!!sym("subject_Id") , row.names.x. ,  Estimate ) %>%
       tidyr::spread(row.names.x., Estimate )
     fname_Pairsplot_Coef <- paste0("Coef_Pairsplot_", self$modelName,".pdf")
     Pairsplot_Coef <-  GGally::ggpairs(forPairs, columns = 2:ncol(forPairs))

   },
   anova_histogram = function(){
     ## Anova_p.values
     Model_Anova <- self$get_anova()
     fname_histogram_anova_p.values <- paste0("Anova_p.values_", self$modelName, ".pdf")
     histogram_anova_p.values <-  Model_Anova %>%
       dplyr::filter(rownames.x. != "Residuals") %>%
       ggplot( aes(x = Pr..F., group = rownames.x.)) +
       geom_histogram(breaks = seq(0,1,by = 0.05)) +
       facet_wrap(~rownames.x.)

   }



  )
)

#' visualize workflow model analyse results
#'
#' used in p2901
#'
#' @export
#' @keywords internal
#' @examples
#'
#' D <- LFQServiceData::ionstar$normalized()
#' D$data <- dplyr::filter(D$data, protein_Id %in% sample(protein_Id, 10))
#' D$config$table$getWorkIntensity()
#' modelName <- "f_condtion_r_peptide"
#' formula_randomPeptide <-
#'   make_custom_model_lmer("transformedIntensity  ~ dilution. + (1 | peptide_Id)",
#'    model_name = modelName)
#' modellingResult <-  LFQService:::model_analyse(
#'  D$data,
#'  formula_randomPeptide,
#'  D$config$table$hkeysDepth(),modelName)
#'
#' modelSummary <- model_analyse_summarize(modellingResult$modelProtein)
#'
#' res <- model_analyse_summarize_vis(modelSummary,
#'  D$config$table$hkeysDepth())
#'
#' res$histogram_coeff_p.values
#' res$VolcanoPlot
#' res$Pairsplot_Coef
#' res$histogram_anova_p.values
#'
model_analyse_summarize_vis <- function(modellingResult,
                                        subject_Id ="protein_Id") {
  Model_Coeff <- tidyr::unite(modellingResult$Model_Coeff, "subject_Id", subject_Id)
  Model_Anova <- tidyr::unite(modellingResult$Model_Anova, "subject_Id", subject_Id)
  modelName <- modellingResult$modelName
  fig <- list()

  ## Coef_Histogram
  fig$fname_histogram_coeff_p.values <- paste0("Coef_Histogram_",modelName,".pdf")
  fig$histogram_coeff_p.values <- ggplot(data = Model_Coeff, aes(x = Pr...t.., group = row.names.x.)) +
    geom_histogram(breaks = seq(0,1,by = 0.05)) +
    facet_wrap(~row.names.x.)

  ## Coef_VolcanoPlot
  fig$fname_VolcanoPlot <- paste0("Coef_VolcanoPlot_",modelName,".pdf")
  fig$VolcanoPlot <- Model_Coeff %>%
    dplyr::filter(row.names.x. != "(Intercept)") %>%
    LFQService::multigroupVolcano(
      effect = "Estimate",
      p.value = "Pr...t..",
      condition = "row.names.x.",
      label = "subject_Id" ,
      xintercept = c(-1, 1) ,
      colour = "isSingular" )

  ## Coef_Pairsplot
  forPairs <- Model_Coeff %>%
    dplyr::select(!!sym("subject_Id") , row.names.x. ,  Estimate ) %>%
    tidyr::spread(row.names.x.,Estimate )
  fig$fname_Pairsplot_Coef <- paste0("Coef_Pairsplot_",modelName,".pdf")
  fig$Pairsplot_Coef <-  GGally::ggpairs(forPairs, columns = 2:ncol(forPairs))

  ## Anova_p.values
  fig$fname_histogram_anova_p.values <- paste0("Anova_p.values_", modelName, ".pdf")
  fig$histogram_anova_p.values <-  modellingResult$Model_Anova %>% dplyr::filter(rownames.x. != "Residuals") %>%
    ggplot( aes(x = Pr..F., group = rownames.x.)) +
    geom_histogram(breaks = seq(0,1,by = 0.05)) +
    facet_wrap(~rownames.x.)

  return(fig)
}

#' Writes figures generated by `model_analyse_summarize_vis`
#'
#' @export
#' @keywords internal
model_analyse_summarize_vis_write <- function(modelling_result,
                                              path,
                                              fig.width = 10 ,
                                              fig.height = 10,
                                              all = FALSE){
  if (all) {
    fpath <- file.path(path, modelling_result$fname_histogram_coeff_p.values)
    message("Writing figure into : ", fpath, "\n")
    pdf(fpath, width = fig.width, height = fig.height )
    print(modelling_result$histogram_coeff_p.values)
    dev.off()

    fpath <- file.path(path, modelling_result$fname_VolcanoPlot)
    message("Writing figure into : ", fpath, "\n")
    pdf(fpath,
        width = fig.width , height = fig.height)
    print(modelling_result$VolcanoPlot)
    dev.off()

    fpath <- file.path(path, modelling_result$fname_Pairsplot_Coef)
    message("Writing figure into : ", fpath, "\n")
    pdf(fpath, width = fig.width , height = fig.height)
    print(modelling_result$Pairsplot_Coef)
    dev.off()
  }
  fpath <- file.path(path, modelling_result$fname_histogram_anova_p.values)
  message("Writing figure into : ", fpath, "\n")
  pdf(fpath, width = fig.width , height = fig.height)
  print(modelling_result$histogram_anova_p.values)
  dev.off()
}

#' workflow_model_analyse
#' @export
#' @references function with paramter path
#' @keywords internal
#' @examples
#' D <- LFQServiceData::ionstar$normalized()
#' D$data <- dplyr::filter(D$data, protein_Id %in% sample(protein_Id,12))
#' modelName <- "f_condtion_r_peptide"
#' formula_randomPeptide <-
#'   make_custom_model_lmer("transformedIntensity  ~ dilution. + (1 | peptide_Id)",
#'   model_name = modelName)
#' modellingResult <-  workflow_model_analyse(D$data,
#'  formula_randomPeptide,
#'   modelName,
#'  subject_Id = D$config$table$hkeysDepth())
#' reslist <- modellingResult()
workflow_model_analyse <- function(data,
                                   modelFunction,
                                   modelName = modelFunction$model_name,
                                   subject_Id = "protein_Id"){

  modellingResult <- model_analyse(data,
                                   modelFunction,
                                   modelName = modelName,
                                   subject_Id)

  # delay write
  res_fun <- function(path = NULL, all = FALSE, DEBUG = FALSE){
    if (DEBUG) {
      return(list(
        modellingResult = modellingResult,
        modelName = modelName,
        subject_Id = subject_Id
      ))
    }

    summaryResult <- model_analyse_summarize(modellingResult$modelProtein,
                                             modelName = modelName,
                                             subject_Id = subject_Id)
    visualization <- model_analyse_summarize_vis(summaryResult, subject_Id)

    if (!is.null(path)) {
      model_analyse_summarize_write(summaryResult, path, all = all)
      model_analyse_summarize_vis_write(visualization, path, all = all)
    }
    return(list(modellingResult = modellingResult,
                summaryResult = summaryResult,
                visualization = visualization))
  }
  return(res_fun)
}


#' p2621 workflow likelihood ratio test
#' TODO: deprecate
#' @keywords internal
#' @export
#' @examples
#' #todo add example
workflow_likelihood_ratio_test <- function(modelProteinF,
                                           modelName,
                                           modelProteinF_Int,
                                           modelName_Int,
                                           subject_Id = "protein_Id",
                                           path = NULL
){
  # Model Comparison
  reg <- dplyr::inner_join(dplyr::select(modelProteinF, !!sym(subject_Id), "linear_model"),
                           dplyr::select(modelProteinF_Int, !!sym(subject_Id), "linear_model") , by = subject_Id)

  reg <- reg %>% dplyr::mutate(modelComparisonLikelihoodRatioTest = map2(!!sym("linear_model.x"),
                                                                         !!sym("linear_model.y"),
                                                                         .likelihood_ratio_test ))
  likelihood_ratio_test_result <- reg %>%
    dplyr::select(!!sym(subject_Id), modelComparisonLikelihoodRatioTest) %>%
    tidyr::unnest(cols = c("modelComparisonLikelihoodRatioTest"))
  likelihood_ratio_test_result <- likelihood_ratio_test_result %>%
    dplyr::rename(likelihood_ratio_test.pValue = modelComparisonLikelihoodRatioTest)


  if (!is.null(path)) {
    fileName <- paste("hist_LRT_", modelName, "_", modelName_Int, ".pdf", sep = "")
    fileName <- file.path(path, fileName)
    message("writing figure : " , fileName , "\n")
    pdf(fileName)
    par(mfrow = c(2, 1))
    hist(likelihood_ratio_test_result$likelihood_ratio_test.pValue,
         breaks = 20)
    plot(ecdf(
      likelihood_ratio_test_result$likelihood_ratio_test.pValue
    ))
    abline(v = c(0.01, 0.05), col = c(3, 2))
    dev.off()
  }

  return(likelihood_ratio_test_result)
}



